service: pdf-service
provider:
  name: aws
  runtime: python3.7
  # Set environment variable for the S3 bucket
  environment:
    S3_BUCKET_NAME: ${file(./config.yml):BucketName}
    # Set env config for fonts to help with kerning
    FONTCONFIG_PATH: '/var/task/fonts'
    FONTCONFIG_FILE: '/var/task/fonts/fonts.conf'
  # Gives our functions full read and write access to the S3 Bucket
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource:
          - arn:aws:s3:::${file(./config.yml):BucketName}
          - arn:aws:s3:::${file(./config.yml):BucketName}/*
functions:
  generate_pdf:
    handler: handler.generate_pdf
    events:
      - http:
          path: new-pdf
          method: post
          cors: true
resources:
 # Creates an S3 bucket in our AWS account
 Resources:
   NewResource:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${file(./config.yml):BucketName}
       CorsConfiguration:
         CorsRules:
           - AllowedMethods:
               - GET
               - HEAD
             AllowedOrigins:
               - "*"
       LifecycleConfiguration:
         Rules:
           -
             ExpirationInDays: 1
             Prefix: '/'
             Status: Enabled
custom:
  pythonRequirements:
    dockerizePip: true
plugins:
  - serverless-python-requirements
